disable building blender
currently, building blender fails to builds with:

    In file included from /usr/include/openvdb/tools/LevelSetRebuild.h:11,
                     from /usr/include/openvdb/tools/GridTransformer.h:16,
                     from /usr/include/openvdb/tools/Clip.h:16,
                     from /<<PKGBUILDDIR>>/intern/openvdb/intern/openvdb_dense_convert.h:34,
                     from /<<PKGBUILDDIR>>/intern/openvdb/openvdb_capi.cc:27:
    /usr/include/openvdb/tools/VolumeToMesh.h:21:10: fatal error: tbb/task_scheduler_init.h: No such file or directory
       21 | #include <tbb/task_scheduler_init.h>
          |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.

This is because tbb dropped the tbb/task_scheduler_init.h header. Fixing this
has to happen in openvdb but the proper fix will be to add support for onetbb
to openvdb because tbb developers changed the name to onetbb:
https://github.com/oneapi-src/oneTBB
Tracking bug in Debian:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1011215
OpenVDB bug:
https://github.com/AcademySoftwareFoundation/openvdb/issues/1366